name:                LPPaver2
version:             0.1.0.0
github:              "michalkonecny/branch-and-prune"
license:             BSD-3-Clause
author:              "Michal Konecny, Junaid Rasheed"
maintainer:          "mikkonecny@gmail.com"
copyright:           "2025 Michal Konecny, Junaid Rasheed"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michalkonecny/LPPaver2#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hashable
- monad-logger
- bytestring
- text
- time
- unliftio-core
- aeson
- hedis
- mixed-types-num
- aern2-mp
- aern2-affarith
- branch-and-prune

default-extensions:
- GHC2021
- RebindableSyntax
- DuplicateRecordFields
- RecordWildCards
- OverloadedRecordDot
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-orphans

library:
  source-dirs: src

executables:
  lppaver2-example:
    main:                runExample.hs
    source-dirs:         cli-app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LPPaver2
